### PR TITLE
[#22] Error parsing condition with key 0:

### PR DESCRIPTION
**Pull request by goldsky**

### CODE REVIEW

**Comment by bertoost** [comment]
Can you tell me what's the difference between your where() string and the original where() array? I don't see it.

**Comment by markwillis82** [comment]
Related to #27 - The problem is XPDO removes the possible blind sql injection and the query fails

**Comment by adamwintle** [comment]
We encountered this today, it floods the error log

**Comment by bertoost** [comment]
Fixed since v2.0.6. Thanks.

**Pull request closed without merging**
