### PR TITLE
Updated regex redirect checker.

### PR DESCRIPTION
**Pull request by markwillis82**
This resolves the issue regarding regex statements and 404 pages not loading.

### CODE REVIEW

**Comment by bertoost** [comment]
Can you give me an example?
Did you test this with many records? And I mean hundreds?
I think it's faster to make the query search instead of walking over all recordds, which are loaded as objects...

**Comment by markwillis82** [comment]
Below are benchmarks and notes on why I took this approach to fix the issue Redirector has. Obviously speed is an important factor in website performance, but site security is of paramount importance.

Table size:

```
mysql> SELECT COUNT(id) FROM modx_redirects;
+-----------+
| COUNT(id) |
+-----------+
|      4182 |
+-----------+
```

Current SQL option:

``` sql
SELECT `modRedirect`.`id` AS `modRedirect_id`, `modRedirect`.`pattern` AS `modRedirect_pattern`, `modRedirect`.`target` AS `modRedirect_target`,
          `modRedirect`.`context_key` AS `modRedirect_context_key`, `modRedirect`.`triggered` AS `modRedirect_triggered`,
          `modRedirect`.`triggered_first` AS `modRedirect_triggered_first`, `modRedirect`.`triggered_last` AS `modRedirect_triggered_last`,
          `modRedirect`.`active` AS `modRedirect_active` FROM `modx_redirects` AS `modRedirect`
  WHERE  ('forum/Topics.aspx' REGEXP `modRedirect`.`pattern` OR 'forum/Topics.aspx' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))
          AND ( (`modRedirect`.`context_key` = 'web' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '') AND `modRedirect`.`active` = 1 )

Total time: 1.547s [1.541s exec, 0.006s fetch]
```

Using an explain:

```
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
| id | select_type | table       | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
|  1 | SIMPLE      | modRedirect | ALL  | active        | NULL | NULL    | NULL | 4182 | Using where |
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
```

No index is being used

Also - given the latest changes in modx (sql injection within xpdo) the ACTUAL query that executes is (as the blind sql injection in the plugin gets removed! this causes the 404s to fail as it always matches the first result):

``` SQL
SELECT `modRedirect`.`id` AS `modRedirect_id`, `modRedirect`.`pattern` AS `modRedirect_pattern`, `modRedirect`.`target` AS `modRedirect_target`,
    `modRedirect`.`context_key` AS `modRedirect_context_key`, `modRedirect`.`triggered` AS `modRedirect_triggered`, `modRedirect`.`triggered_first` AS `modRedirect_triggered_first`,
    `modRedirect`.`triggered_last` AS `modRedirect_triggered_last`, `modRedirect`.`active` AS `modRedirect_active`
    FROM `modx_redirects` AS `modRedirect` WHERE  ( (`modRedirect`.`context_key` = 'web' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '') AND `modRedirect`.`active` = 1 )
```

NEW php approach:

SQL to run:

``` SQL
SELECT `modRedirect`.`id` AS `modRedirect_id`, `modRedirect`.`pattern` AS `modRedirect_pattern`, `modRedirect`.`target` AS `modRedirect_target`, 
  `modRedirect`.`context_key` AS `modRedirect_context_key`, `modRedirect`.`triggered` AS `modRedirect_triggered`, 
  `modRedirect`.`triggered_first` AS `modRedirect_triggered_first`, `modRedirect`.`triggered_last` AS `modRedirect_triggered_last`, 
  `modRedirect`.`active` AS `modRedirect_active` FROM `modx_redirects` AS `modRedirect` WHERE 
  (  ( `modRedirect`.`pattern` LIKE '%*%' OR `modRedirect`.`pattern` LIKE '%?%' )  AND 
  (`modRedirect`.`context_key` = 'web' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '') AND `modRedirect`.`active` = 1 ) 
```

Total time: 0.007s [0.003s exec, 0.004s fetch]

Using an explain:

```
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
| id | select_type | table       | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
|  1 | SIMPLE      | modRedirect | ALL  | active        | NULL | NULL    | NULL | 4182 | Using where |
+----+-------------+-------------+------+---------------+------+---------+------+------+-------------+
```

No index is being used - but the sql is more efficient. However adding a compound index on "active, context_key, pattern" changes the execution massively:

```
+----+-------------+-------------+------+--------------------------+-------------------+---------+-------+------+-----------------------+
| id | select_type | table       | type | possible_keys            | key               | key_len | ref   | rows | Extra                 |
+----+-------------+-------------+------+--------------------------+-------------------+---------+-------+------+-----------------------+
|  1 | SIMPLE      | modRedirect | ref  | UK_modx_redirects,active | UK_modx_redirects | 1       | const |   41 | Using index condition |
+----+-------------+-------------+------+--------------------------+-------------------+---------+-------+------+-----------------------+
```

## Some benchmarks.

#### New Code

we are seeing the difference between the two methods - ignoring the fact page loads are slow as no caching is on, etc

running `siege -v -b -c1 -t 1M <url>` hitting a VALID redirect:

```
Transactions:                 64 hits
Availability:             100.00 %
Elapsed time:              59.51 secs
Data transferred:           0.00 MB
Response time:              0.92 secs
Transaction rate:           1.08 trans/sec
Throughput:             0.00 MB/sec
Concurrency:                0.99
Successful transactions:          64
Failed transactions:               0
Longest transaction:            1.10
Shortest transaction:           0.89
```

running `siege -v -b -c1 -t 1M <url>` hitting a 404 and no valid redirect:

```
Transactions:                 54 hits
Availability:             100.00 %
Elapsed time:              59.17 secs
Data transferred:           0.25 MB
Response time:              1.08 secs
Transaction rate:           0.91 trans/sec
Throughput:             0.00 MB/sec
Concurrency:                0.99
Successful transactions:           0
Failed transactions:               0
Longest transaction:            1.11
Shortest transaction:           0.00
```

#### Existing Code

running siege and xpdo query for existing code:

```
Transactions:                 38 hits
Availability:             100.00 %
Elapsed time:              59.86 secs
Data transferred:           0.00 MB
Response time:              1.55 secs
Transaction rate:           0.63 trans/sec
Throughput:             0.00 MB/sec
Concurrency:                0.99
Successful transactions:          38
Failed transactions:               0
Longest transaction:            1.57
Shortest transaction:           1.54
```

For this test I had to run the following code (as the latest version of modx breaks the current sql statement).

``` PHP
$redirect = $modx->query("SELECT `modRedirect`.`id` AS `modRedirect_id`, `modRedirect`.`pattern` AS `modRedirect_pattern`, `modRedirect`.`target` AS `modRedirect_target`,
          `modRedirect`.`context_key` AS `modRedirect_context_key`, `modRedirect`.`triggered` AS `modRedirect_triggered`,
          `modRedirect`.`triggered_first` AS `modRedirect_triggered_first`, `modRedirect`.`triggered_last` AS `modRedirect_triggered_last`,
          `modRedirect`.`active` AS `modRedirect_active` FROM `modx_redirects` AS `modRedirect`
  WHERE  ('forum/Topics.aspx' REGEXP `modRedirect`.`pattern` OR 'forum/Topics.aspx' REGEXP CONCAT('^', `modRedirect`.`pattern`, '$'))
          AND ( (`modRedirect`.`context_key` = 'web' OR `modRedirect`.`context_key` IS NULL OR `modRedirect`.`context_key` = '') AND `modRedirect`.`active` = 1 )");
```

Not only is the php version more secure (removing any possible blind sql injection) but also quicker.

**Comment by amdbuilder** [comment]
This issue is effecting our site as well, the 404 page cannot be reached because redirector is sending the user to another page. DIsabling the plugin fixes the problem.

**Comment by markwillis82** [comment]
Can we get this merged and updated please?

**Comment by Mark-H** [comment]
+1 for resolving the inability to get to the 404 page.

**Comment by vierkantemeter** [comment]
Can you please release redirector 2.0.6 with this commit?

**Pull request merged**
