### PR TITLE
Move Ext.onReady from js to the home controller

### PR DESCRIPTION
**Pull request by danyaPostfactum**
AjaxManager compatibility fix

### CODE REVIEW

**Comment by danyaPostfactum** [comment]
Could you merge this, please? I know, AM plugin is not much popular, but still there are 
are dozens (or hundreds) of users. This is very little change, why not?

**Comment by jpdevries** [comment]
@bertoost when you get a chance can you test and review this PR?

**Comment by bertoost** [comment]
I cannot merge this into the modxcms repository :-( don't have permissions here :p

**Comment by jpdevries** [comment]
@bertoost i merged this for ya, but i'm not sure if you included it in the 2.0.4 build? looks like not

**Pull request merged**
